# Generated by Django 4.0.4 on 2022-06-03 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.in_.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20180616_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMissing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(null=True, upload_to='missing/')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=90, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, verbose_name='Sex')),
                ('dob', models.DateField()),
                ('date_of_missing', models.DateField(verbose_name='Date of Missing')),
                ('time_of_missing', models.TimeField(verbose_name='Time of Missing')),
                ('filed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('extra_info', models.TextField(max_length=180, verbose_name='Addition Info')),
                ('street', models.CharField(max_length=128, verbose_name='Street')),
                ('area', models.CharField(max_length=128, verbose_name='Area')),
                ('city', models.CharField(default='Bangalore', max_length=64, verbose_name='City')),
                ('state', localflavor.in_.models.INStateField(max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Pin code')),
                ('status', models.CharField(choices=[('Not found', 'Not found'), ('Found', 'Found')], default='Not found', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
