# Generated by Django 4.0.4 on 2022-06-06 17:54

from django.db import migrations, models
import localflavor.in_.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_filemissing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('img_id', models.CharField(max_length=100)),
                ('img', models.ImageField(null=True, upload_to='found/')),
                ('found_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('street', models.CharField(max_length=128, verbose_name='Street')),
                ('area', models.CharField(max_length=128, verbose_name='Area')),
                ('city', models.CharField(default='Bangalore', max_length=64, verbose_name='City')),
                ('state', localflavor.in_.models.INStateField(max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Pin code')),
            ],
        ),
    ]
