# Generated by Django 4.0.4 on 2022-05-23 16:41

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import localflavor.in_.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_remove_person_department_remove_person_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMissing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/missing'), upload_to='')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=90, verbose_name='Last name')),
                ('dob', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('date_of_missing', models.DateField(auto_now_add=True, verbose_name='Date of Missing')),
                ('time_of_missing', models.TimeField(auto_now_add=True, verbose_name='Time of Missing')),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('street', models.CharField(max_length=128, verbose_name='Street')),
                ('area', models.CharField(blank=True, max_length=128, verbose_name='Area')),
                ('city', models.CharField(default='Bangalore', max_length=64, verbose_name='City')),
                ('state', localflavor.in_.models.INStateField(max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Pin code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
