# Generated by Django 4.0.4 on 2022-05-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_filemissing_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemissing',
            name='img_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filemissing',
            name='status',
            field=models.CharField(choices=[('Not found', 'Not found'), ('Found', 'Found')], default='Not found', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='filemissing',
            name='area',
            field=models.CharField(max_length=128, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='filemissing',
            name='date_of_missing',
            field=models.DateField(verbose_name='Date of Missing'),
        ),
        migrations.AlterField(
            model_name='filemissing',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='filemissing',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='filemissing',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='filemissing',
            name='last_name',
            field=models.CharField(max_length=90, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='filemissing',
            name='time_of_missing',
            field=models.TimeField(verbose_name='Time of Missing'),
        ),
    ]
