# Generated by Django 4.0.4 on 2022-05-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_filemissing_img_id_filemissing_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemissing',
            name='filed_at',
        ),
        migrations.AlterField(
            model_name='filemissing',
            name='img',
            field=models.ImageField(null=True, upload_to='missing/'),
        ),
    ]
