# Generated by Django 4.0.4 on 2022-05-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_filemissing_filed_at_alter_filemissing_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemissing',
            name='extra_info',
            field=models.TextField(max_length=200, null=True, verbose_name='Addition Info'),
        ),
        migrations.AddField(
            model_name='filemissing',
            name='filed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='filemissing',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='filemissing',
            name='dob',
            field=models.DateField(),
        ),
    ]
